export const ActionTypes = {
  SLIDE_SHOW: "SLIDE_SHOW",
  ADD_MOVIES: "ADD_MOVIES",
  ADD_MOVIE_TO_LIST: "ADD_MOVIE_TO_LIST",
  REMOVE_MOVIE_FROM_LIST: "REMOVE_MOVIE_FROM_LIST",
  SET_LINKACTIVE: "SET_LINKACTIVE",
  ADD_POST_MOVIES: "ADD_POST_MOVIES",
  LOADING : "LOADING",
};
